//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaModelLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int ID { get; set; }
        public int ContID { get; set; }
        public int Pin { get; set; }
    
        public virtual Cont Cont { get; set; }
    }
}
