//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaModelLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cont
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cont()
        {
            this.Cards = new HashSet<Card>();
        }
    
        public int ID { get; set; }
        public string IBAN { get; set; }
        public int ClientID { get; set; }
        public string Moneda { get; set; }
        public decimal Sold { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card> Cards { get; set; }
        public virtual Client Client { get; set; }
    }
}
